#!/usr/bin/env bash

# Dark Pastels colors
# based on xfce4-terminal color scheme

black="#3F3F3F"
red="#DCA3A3"
green="#72D5A3"
yellow="#DFAF8F"
blue="#94BFF3"
magenta="#EC93D3"
cyan="#93E0E3"
white="#FFFFFF"
gray="#DCDCDC"

FG="#DCDCDC"
BG="#3F3F3F"
LABEL="#DCA3A3"
cmus="#d8c89d"

