#!/usr/bin/env bash

# Everforest colors

black="#3C3C3C"
red="#e67e80"
green="#a7c080"
yellow="#dbbc7f"
blue="#7fbbb3"
purple="#d699b6"
cyan="#83c092"
white="#A89984"
gray="#beb9af"

FG="#beb9af"
BG="#323D43"
LABEL="#7fbbb3"
cmus="#d699b6"
