#!/usr/bin/env bash

# dmenu theming
. $HOME/.local/bin/dmenu-scripts/dmenu-theming

first_prompt="O que você quer?"
opt1="Sair do i3\nReiniciar\nDesligar\nSuspender"
opt2="Sim\nNão"


ask() {
    answer="$( echo -e $1 | dmenu -i -p "$2" $lines $colors $font )"
}

ask "$opt1" "$first_prompt"

case $answer in
    "Sair do i3")
        ask "$opt2" "Quer mesmo sair do i3wm?"
        if [[ $answer == "Sim" ]]; then
            i3-msg exit || bspc quit
        fi
        exit 0
        ;;
    "Reiniciar")
        ask "$opt2" "Quer mesmo reiniciar o sistema?"
        if [[ $answer == "Sim" ]]; then
            systemctl reboot
        fi
        exit 0
        ;;
    "Desligar")
        ask "$opt2" "Quer mesmo desligar o computador?"
        if [[ $answer == "Sim" ]]; then
            systemctl poweroff
        fi
        exit 0
        ;;

    "Suspender")
        ask "$opt2" "Quer mesmo suspender o computador?"
        if [[ $answer == "Sim" ]]; then
            systemctl suspend
        fi
        exit 0
        ;;
esac

exit 0
